# Generated by Django 3.0.4 on 2020-03-27 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ip_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'Network Site', 'verbose_name_plural': 'Network Sites'},
        ),
        migrations.AddField(
            model_name='device',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='vlan',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='ip_addresses', to='ip_manager.Subnet', verbose_name='Subnet'),
        ),
    ]
