# Generated by Django 3.0.4 on 2020-03-27 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ip_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Location',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Network Location',
                     'verbose_name_plural': 'Network Locations'},
        ),
        migrations.AlterModelOptions(
            name='vlan',
            options={'ordering': ('vid', 'pk'), 'verbose_name': 'VLAN', 'verbose_name_plural': 'VLANs'},
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='site',
            new_name='location',
        ),
        migrations.AlterModelTable(
            name='location',
            table='Locations',
        ),
    ]
